name: Wheels

# Publish when a (published) GitHub Release is created.
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          # Keep in sync with ``build-system.requires`` in ``pyproject.toml``.
          # python -m pip install --upgrade setuptools pip wheel build cython
          # python -m pip install -r requirements.txt
          # # Keep in sync with ``project.optional-dependencies.doc`` in ``pyproject.toml``.
          # python -m pip install 'sphinx>=1.1,<6' sphinx_rtd_theme numpydoc ipython
          python -m pip install pip-tools
          pip-compile --generate-hashes requirements.in
          cat requirements.txt

    
